"""empty message

Revision ID: 32a5ac7d5cbe
Revises: 8229820bdeea
Create Date: 2020-04-07 21:11:43.052475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a5ac7d5cbe'
down_revision = '8229820bdeea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(length=75),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(length=75),
               nullable=False)
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
