"""empty message

Revision ID: 8229820bdeea
Revises: 11f155f13aec
Create Date: 2020-04-07 18:07:55.366497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8229820bdeea'
down_revision = '11f155f13aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_first_name', table_name='user')
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.drop_index('ix_user_last_name', table_name='user')
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.create_index('ix_user_last_name', 'user', ['last_name'], unique=1)
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.create_index('ix_user_first_name', 'user', ['first_name'], unique=1)
    # ### end Alembic commands ###
