"""empty message

Revision ID: 984120a385bb
Revises: bcb4fece21a9
Create Date: 2020-04-07 21:25:02.486109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984120a385bb'
down_revision = 'bcb4fece21a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=75),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=75),
               nullable=False)

    # ### end Alembic commands ###
