"""empty message

Revision ID: ab9363b515af
Revises: 63b64c7bc23b
Create Date: 2020-04-08 21:14:12.215126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9363b515af'
down_revision = '63b64c7bc23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('card_cvv')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_cvv', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
