"""empty message

Revision ID: e052856485d8
Revises: db6eb1007fc7
Create Date: 2020-04-07 16:23:50.691882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e052856485d8'
down_revision = 'db6eb1007fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_val', sa.Integer(), nullable=False))
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_index('ix_user_first_name', table_name='user')
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.drop_index('ix_user_last_name', table_name='user')
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.create_index('ix_user_last_name', 'user', ['last_name'], unique=1)
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.create_index('ix_user_first_name', 'user', ['first_name'], unique=1)
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('user', 'email_val')
    # ### end Alembic commands ###
